<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="4" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="org.forgerock.openidm.provisioner.IdTest" duration-ms="39" started-at="2014-07-22T15:17:59Z" finished-at="2014-07-22T15:18:00Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="39" started-at="2014-07-22T15:17:59Z" finished-at="2014-07-22T15:18:00Z">
      <class name="org.forgerock.openidm.provisioner.IdTest">
        <test-method status="PASS" signature="testExpectObjectId()[pri:0, instance:org.forgerock.openidm.provisioner.IdTest@20ebd7c4]" name="testExpectObjectId" duration-ms="23" started-at="2014-07-22T17:17:59Z" finished-at="2014-07-22T17:18:00Z">
          <exception class="org.forgerock.json.resource.BadRequestException">
            <message>
              <![CDATA[Invalid number of tokens in ID /system/xml/]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.forgerock.json.resource.BadRequestException: Invalid number of tokens in ID /system/xml/
	at org.forgerock.openidm.provisioner.Id.<init>(Id.java:146)
	at org.forgerock.openidm.provisioner.IdTest.testExpectObjectId(IdTest.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- org.forgerock.json.resource.BadRequestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testExpectObjectId -->
        <test-method status="PASS" signature="testId()[pri:0, instance:org.forgerock.openidm.provisioner.IdTest@20ebd7c4]" name="testId" duration-ms="4" started-at="2014-07-22T17:18:00Z" finished-at="2014-07-22T17:18:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testId -->
        <test-method status="PASS" signature="testMalformedURLPrefix()[pri:0, instance:org.forgerock.openidm.provisioner.IdTest@20ebd7c4]" name="testMalformedURLPrefix" duration-ms="0" started-at="2014-07-22T17:18:00Z" finished-at="2014-07-22T17:18:00Z">
          <exception class="org.forgerock.json.resource.BadRequestException">
            <message>
              <![CDATA[Invalid number of tokens in ID /system/xml/]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.forgerock.json.resource.BadRequestException: Invalid number of tokens in ID /system/xml/
	at org.forgerock.openidm.provisioner.Id.<init>(Id.java:146)
	at org.forgerock.openidm.provisioner.IdTest.testMalformedURLPrefix(IdTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- org.forgerock.json.resource.BadRequestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMalformedURLPrefix -->
        <test-method status="PASS" signature="testResolveLocalId()[pri:0, instance:org.forgerock.openidm.provisioner.IdTest@20ebd7c4]" name="testResolveLocalId" duration-ms="0" started-at="2014-07-22T17:18:00Z" finished-at="2014-07-22T17:18:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResolveLocalId -->
      </class> <!-- org.forgerock.openidm.provisioner.IdTest -->
    </test> <!-- Command line test -->
  </suite> <!-- org.forgerock.openidm.provisioner.IdTest -->
</testng-results>
